### ISSUE TITLE
Use a Scalable Vector Graphics (SVG) and delete all PNGs

### ISSUE THREAD

**Issue by x80486** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#1]
If and when **JetBrains** replies back with the SVG file.

**Comment by FakeShemp** [comment]
@x80486 The SVG is in the `/bin` directory in the tar already, right?

**Comment by x80486** [comment]
Indeed, I saw they just included it since version `2018.3`, but since this one was in review for a while, I was only updating the `.tar.gz` without checking the content.

I'll include make the change in the next release since it's not a deal breaker.
