### ISSUE TITLE
uses filesystem=host

### ISSUE THREAD

**Issue by alexmo1997** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#101]
Using filesystem=host breaks all sandboxing functionality of flatpak and is thus inherently insecure.
It should be possible to implement the needed functionality with xdg portals and such.

**Comment by x80486** [comment]
I'm not sure where this falls. It looks like something JetBrains might need to implement. They don't support this format, so there is really nothing actionable for me here.
