### ISSUE TITLE
Can't use docker-compose via Docker plugin

### ISSUE THREAD

**Issue by DanielNoga** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#109]
Can't use docker-compose in IDEA. I tried to use /var/run/host/usr/bin/docker-compose, but it ended with python errors. I tried to use /var/run/host/usr/bin/docker with v2, but IDEA throws some error about unknown -f flag.

**Comment by x80486** [comment]
A [pull request](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/pull/158) was merged with some changes that should fix this. Please, reopen or create a new issue if it doesn't solve the problem on your end.
