### ISSUE TITLE
Cannot access to microphone

### ISSUE THREAD

**Issue by tunix** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#115]
Hi,

For Code With Me sessions, I wanted to start a call. I was able to give access to my camera (via Flatseal) but not to the microphone. Is there anything we can do about this on flatpak side?

**Comment by x80486** [comment]
How did you give access to your camera? I think what's missing on this manifest is `--device=all`, but I guess that's what you might have set in `Flatseal`.

**Comment by tunix** [comment]
Yes, I set that inside Flatseal but access to the microphone is still not available.

**Comment by x80486** [comment]
I will have to take a look at this one. As far as I can tell, `--device=all` should do it, but it could be that there is a missing dependency or `IntelliJ IDEA` is unable to use this functionality correctly — through portals, etc.

**Comment by x80486** [comment]
@tunix, there were some permissions added recently that may fix this issue. Can you download the latest update and let me know?
