### ISSUE TITLE
Access to flatpak runtimes

### ISSUE THREAD

**Issue by tunix** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#117]
Hi,

I'd like to use IntelliJ IDEA's built-in capabilities for NodeJS development but currently I can't use it with the Node runtime. Webstorm flatpak can make use of other runtimes with this: https://github.com/Lctrs/jetbrains-flatpak-wrapper/tree/1d4aa305511587c575ec40293d52bb04ce23623e

Is it possible to integrate this project with this package?

**Comment by x80486** [comment]
Feel free to reopen this one or create a new one. I just integrated the Flatpak wrapper to allow this — along with some other changes that will fix another issue you were facing.
