### ISSUE TITLE
gpg: signing failed: No pinentry

### ISSUE THREAD

**Issue by motorto** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#134]
Using the last version I get the following error when trying to sign a message trough the terminal on the IDE

```
$ echo "a" | gpg --clearsign
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

a
gpg: signing failed: No pinentry
gpg: [stdin]: clear-sign failed: No pinentry
```

**Comment by x80486** [comment]
Was this working before? You mentioned "using the last version", so I infer that it was working and now it isn't. If that's the case, can you check with the latest update?

**Comment by motorto** [comment]
Sorry for the wait, yes it used to work, but to be honest I gave up in using the flatpak version and used the toolbox method instead. 

Thanks for the attention , and sorry for the inconvenience.
