### ISSUE TITLE
git/ssh not working

### ISSUE THREAD

**Issue by Bixilon** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#138]
When running `ssh` in the repository, an error occurs (I need that for pushing):
```
[240 preload-host-spawn-strategy] Warning: waitpid override ignores groups
dbus[333]: arguments to dbus_move_error() were incorrect, assertion "(dest) == NULL || !dbus_error_is_set ((dest))" failed in file ../../dbus/dbus-errors.c line 282.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Abgebrochen
[240 preload-host-spawn-strategy] Warning: waitpid override ignores groups
```

Git also does not work in IntelliJ, when pressing `CTRL` + `K´ it always tells me that there are no changes, checking the git log only works partly, it fails because of the dbus error above.

Even when granting all dbus permissions with flatseal, it still fails.

How do I fix this?

Thanks!

**Comment by x80486** [comment]
I think this is all Git-related, so I'll track it in #137 — even though initially they look different.
