### ISSUE TITLE
Markdown files hangs a Flatpak version of IDEA.

### ISSUE THREAD

**Issue by gavrilovegor519** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#141]
Tarball version of IDEA is not hangs on Markdown.
Host: Fedora 38 (with all updates).
What?

**Comment by gavrilovegor519** [comment]
@x80486, publish a #140 commit! Or add policy file quickly.

**Comment by x80486** [comment]
I'm trying to test that build before merging. Did you install it? Have you tested it as well?

**Comment by gavrilovegor519** [comment]
> I'm trying to test that build before merging. Did you install it? Have you tested it as well?

1. Will the installation of this build lead to the connection of the beta repository? I wouldn't like that. 2. Will this build be updated to a stable version? Or will I have to reinstall it?

**Comment by x80486** [comment]
The builds you install from `Flathub` are usually in the `system` namespace; these test builds I install them in the `user` namespace. You can remove it at any point, before or after installing the one from `Flathub` — the release.

**Comment by x80486** [comment]
Great, so it will be fixed as well when this is merged :raised_hands:
