### ISSUE TITLE
Cannot launch: "Cannot connect to already running IDE instance. Exception: Process 2 is still running"

### ISSUE THREAD

**Issue by brittyazel** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#157]
IntelliJ has been running fine up until this point, but today I was hit with a strange issue where I can no longer launch the program. I get this error:

```
Start Failed
Cannot connect to already running IDE instance.
Exception: Process 2 is still running
```

This issue has been reported [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/10865358461202-Intellij-cannot-launch-because-process-2-already-running), but my issue might be different as they're attributing the bug to samba, and I am not using samba.

Uninstalling and reinstalling has not worked, nor has rebooting. I am unsure on what more to do, nor am I sure what triggered this to happen all of a sudden.

**Comment by x80486** [comment]
It basically says there is another instance. Try to search for any `intellij` or `java` process, and kill it. Make sure it's the correct process, because there could be plenty of `java` processes running different things.

**Comment by brittyazel** [comment]
Certainly, however this behavior is happening after a fresh reboot, with it being the first application to be launched. It's highly unlikely that there is any other process running, and I have verified as much from looking at top and system monitor.

I deleted all of my saved configs, and starting fresh seemed to alleviate the issue for the time being. That said, 'something' is triggering this to happen, and I'm concerned it will come back.

**Comment by fjbaldon** [comment]
Happening on mine too.

**Comment by brittyazel** [comment]
Update: It's back again today. Same situation as above.

**Comment by Job79** [comment]
Deleting the lock file at `~/.var/app/com.jetbrains.IntelliJ-IDEA-Ultimate/config/JetBrains/IntelliJIdea2023.2/.lock` fixed the issue for me. Killing the process or reinstalling without deleting the user data doesn't fix this issue.

**Comment by fjbaldon** [comment]
> Deleting the lock file at `~/.var/app/com.jetbrains.IntelliJ-IDEA-Ultimate/config/JetBrains/IntelliJIdea2023.2/.lock` fixed the issue for me. Killing the process or reinstalling without deleting the user data doesn't fix this issue.

Does the issue come back after deleting the file?

**Comment by brittyazel** [comment]
Mine seems to come back randomly. I'm not sure what triggers it, but I have had to delete the .lock file a couple of times now to clear it up.

**Comment by Job79** [comment]
> > Deleting the lock file at `~/.var/app/com.jetbrains.IntelliJ-IDEA-Ultimate/config/JetBrains/IntelliJIdea2023.2/.lock` fixed the issue for me. Killing the process or reinstalling without deleting the user data doesn't fix this issue.
> 
> Does the issue come back after deleting the file?

After some time yes. No idea what triggers it, but it doesn't look like a flatpak problem. People using the official jetbrains toolbox to install intellij are also [experiencing problems](https://intellij-support.jetbrains.com/hc/en-us/community/posts/10865358461202-Intellij-cannot-launch-because-process-2-already-running?page=2).

**Comment by x80486** [comment]
Will close this one since this is not specific to the `Flatpak` package.

This issue was fixed recently so the application should behave accordingly in all formats from now on.
