### ISSUE TITLE
Git lfs repository does not work properly

### ISSUE THREAD

**Issue by DanielNoga** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#160]
How to reproduce:

- git clone __someRepository__ on the host
- git lfs pull on the host
- Run IDEA from flatpak
- Open commit dialog

Now:
- See files downloaded via git lfs pull as changed to be commited

Expected:
- See nothing as changed (as it works correctly in native version on host)

Tested on openSUSE Leap 15.5 with Flatpak version 1.14.4 and latest IDEA from Flatpak

**Comment by x80486** [comment]
`git-lfs` is installed, so the `Git` plugin should be able to use it.

Let me know if that's working now.
