### ISSUE TITLE
Instruction for local shell don't work

### ISSUE THREAD

**Issue by thesteve0** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#167]
In the first_run.txt file it gives instructions for how to permanently set the Intellij terminal to be the local filesystem.

```
To make the Integrated Terminal automatically use the host system's shell,
you can modify `Settings > Tools > Terminal > Shell path` to `/usr/bin/env -- flatpak-spawn --host bash`:
```

1. There is a space between -- and flatpak-spawn which makes the command fail
2. Even when that is fixed the terminal does not appear. I tried running the command in native terminal and this is the error I get `/usr/bin/env: unrecognized option '--flatpak-spawn'` and if I delete the -- I get `/usr/bin/env: ‘flatpak-spawn’: No such file or directory`

I looked at the help for /usr/bin/env and can't figure out what you are trying to do. Can you please update the instructions

**Comment by thesteve0** [comment]
THen I tried to do the run the one off command. I reset the default environment to bash, opened a terminal, and entered the command in the first_run.txt file  ` flatpak-spawn --host bash`

It errors 
```
Portal call failed: Failed to start command: Failed to change to directory “/app/share/jetbrains-flatpak-wrapper” (No such file or directory)
```

**Comment by x80486** [comment]
This is an issue for [this](https://github.com/Lctrs/jetbrains-flatpak-wrapper) repository.

**Comment by thesteve0** [comment]
OK thanks for clearing that up. I was just following the instructions in first_run.txt for where to file an issie

**Comment by x80486** [comment]
> OK thanks for clearing that up. I was just following the instructions in first_run.txt for where to file an issie

It's OK. Most `JetBrains` (if not all) Flatpak applications make use of that "wrapper".

**Comment by thesteve0** [comment]
Yeah new to running things in flatpack that need access to the terminal. I see they mount the host file system by default for the file picker  - which is much appreciated. Filed the issue - thanks!

**Comment by thesteve0** [comment]
Refiled the issue  in the right repo so I will close this issue
