### ISSUE TITLE
IntelliJ IDEA cannot receive filesystem event notifications for the project

### ISSUE THREAD

**Issue by DWolf-19** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#182]
The project is located on my computer, after installing the IDE as flatpak, this started happening. How can I fix it?
![Notification](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/assets/108197792/4e2f6b0a-ef3e-405f-bb95-1c6a703046c2)

OS: Ubuntu 22.04

**Comment by Marcelektro** [comment]
I've got a similar issue, sometimes.
I installed it normally (via extracting the package into a directory) and executing the start shell script.

I notice it when updating maven dependency versions. They are properly downloaded in the .m2 dir, but IJ can't see them in the project itself (everything related to the dependency goes "red" as not found) and in Project Settings in Libraries, the artifacts are red (as if not found), although they're there in the .m2 dir.

**Comment by xanscale** [comment]
i think we just need to add  `--talk-name=org.freedesktop.Notifications` in `finish-args`

**Comment by xanscale** [comment]
the problem persists with last version ?

**Comment by xanscale** [comment]
i dont think we can do anything about that in this wrapper.

i will close for the moment
