### ISSUE TITLE
Outside Java SDK not executable after update - How to get working JDK?

### ISSUE THREAD

**Issue by frhun** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#19]
After a recent update (i'm not sure if it was the Flatpak or the Fedora 29->30 update) all java projects fail to compile. I'm using the Fedora packaged JDK (outside the flatpak).

Project SDK Path inside IntelliJ:
`/run/host/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.fc30.x86_64`

Outside Container:
```
$ls /usr/lib/jvm
java
java-11
java-11-openjdk
java-11-openjdk-11.0.3.7-1.fc30.x86_64
java-12-openjdk-12.0.1.12-1.rolling.fc30.x86_64
java-1.8.0
java-1.8.0-openjdk
java-1.8.0-openjdk-1.8.0.212.b04-0.fc30.x86_64
java-openjdk
jre
jre-11
jre-11-openjdk
jre-11-openjdk-11.0.3.7-1.fc30.x86_64
jre-12
jre-12-openjdk
jre-12-openjdk-12.0.1.12-1.rolling.fc30.x86_64
jre-1.8.0
jre-1.8.0-openjdk
jre-1.8.0-openjdk-1.8.0.212.b04-0.fc30.x86_64
jre-openjdk
openjfx
```

Error that happens when trying to build a simple java app:
```
Error:Abnormal build process termination: 
/var/run/host/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.fc30.x86_64/bin/java -Xmx700m -Djava.awt.headless=true -Djava.endorsed.dirs=\"\" 
 [ ... Many lines of arguments ...]
Error: dl failure on line 893Error: failed /run/host/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so, because /usr/lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by /run/host/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.fc30.x86_64/jre/lib/amd64/server/libjvm.so)
```
Obviously the file does not exist, but it worked before (not sure if it existed then).
The GLIBC version is not mismatched, it works outside the container.

_How do i get a working JDK inside the Flatpak container?_

**Comment by x80486** [comment]
I think you were just lucky all this time 😉...that "type of location" never worked for me.

If you still want to use an "external" SDK, heads up and start using a version manager: `asdf`, `jabba`, etc. — peek into this thread: **How to configure JDK in Intellij on Fedora Silverblue?** in the `Community` edition issue tracker.

Alternatively, you can use the OpenJDK from the Flatpak `Sdk Extensions` — you can find instructions in the aforementioned thread.

**Comment by frhun** [comment]
Installing the SDK Extension from Flathub worked for JDK 11 but somehow not for 8.
I'm not closing this for now until i get 8 to work.
It might also be helpful adding a heads up to the package description to let users know of these optional packages.
