### ISSUE TITLE
Markdown preview doesn't work on Ubuntu 24.04

### ISSUE THREAD

**Issue by Spikhalskiy** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#190]
Markdown previews don't display in Idea installed on Ubuntu 24.04 through flathub. Logs don't contain any relevant errors. Everything works as expected on the installation directly from Intellij tarball.

**Comment by x80486** [comment]
I installed Ubuntu 24.04 and the Flatpak distribution of `IntelliJ IDEA Ultimate` and I see no issues with the preview of Markdown files.

Would you be able to share the file you are trying to preview?

> Notice that sometimes the IDE freezes with the previews (Markdown and AsciiDoc) when you have links to external context. Toggling from preview, back and forth, solves the problem all the time.

**Comment by Spikhalskiy** [comment]
@x80486 it's not file-specific, it manifests on any .md for my system.
![Screenshot from 2024-06-07 14-05-06](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/assets/532108/83e3c215-bca2-4950-9179-b1dcea6a60f2)

**Comment by x80486** [comment]
What do you see in the IDE logs and `systemd` if/when you toggle from editor to editor/preview — or just preview?
