### ISSUE TITLE
AsciiDoc and Markdown plugins don't behave properly

### ISSUE THREAD

**Issue by x80486** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#2]
Both plugins (and maybe some others too) use JavaFX / OpenJFX and these, at the same time, require `libgtk-x11-2.0.so.0` (included in GTK+ `2.x`) to preview/render the view properly. An exception is thrown the first time this is used – and onward.

**Comment by jgarciao** [comment]
There was a problem in the flathub backend that prevented this app from being shown in the website. It's fixed now. I guess it will have more users soon

https://flathub.org/apps/details/com.jetbrains.IntelliJ-IDEA-Ultimate
