### ISSUE TITLE
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true on intellij

### ISSUE THREAD

**Issue by AnasAbdullh** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#200]
I am having trouble running intellij on linux.

> CompileCommand:` exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
> Error: Could not find or load main class d
> Caused by: java.lang.ClassNotFoundException: d 
>

**Comment by x80486** [comment]
Can you describe exactly what are you trying to do?

You can always check the `idea.log` for some clues on what's failing — you can post it here as well.
