### ISSUE TITLE
Can't connect to host's docker socket

### ISSUE THREAD

**Issue by dg98** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#22]
Would it be possible to allow the flatpak to see the host's docker socket (usually located at /var/run/docker.sock)? I had to allow network connections and connect via tcp because I couldn't access it from within the flatpak.

**Comment by thogaw** [comment]
For the moment you simply could override the filesystem permission like:

`sudo flatpak override --filesystem=/run/docker.sock com.jetbrains.IntelliJ-IDEA-Ultimate`

BTW: This also works for VSCode and others ;)

**Comment by conopulis** [comment]
This was 

`flatpak override --user --filesystem=/run/docker.sock com.jetbrains.IntelliJ-IDEA-Ultimate` 

for how my setup works. Override in /var/lib/flatpak/overrides did nothing.

**Comment by davidparks21** [comment]
I'm encountering the same challenges discussed here. I've run both of these commands at a terminal, but nothing has changed and I don't know what I should be expecting or looking for to verify that flatpak is configured to expose the docker daemon. 

Docker is running just fine on my system, but pycharm installed under flatpak continues to be unable to see the docker daemon.

I'm not seeing a lot of other resources beyond this thread in google searches.

**Comment by x80486** [comment]
The `flatpak override --user --filesystem=/run/docker.sock com.jetbrains.IntelliJ-IDEA-Ultimate` works; did you try that via the CLI or just using Flatseal?

Also notice that this is the IntelliJ IDEA repository, not PyCharm — although they both share a great deal.

**Comment by davidparks21** [comment]
Thank you very much! You're right, it works. I was being blatantly oblivious to this being an IntelliJ thread not a Pycharm thread. Woops. 

This does work, below is the equivalent for pycharm. Hopefully it's useful to someone else, google is sending us Pycharm-ers here too.

```
flatpak list   # get the list of applications and Application ID
flatpak override --user --filesystem=/run/docker.sock com.jetbrains.PyCharm-Professional  # the equivalent for pycharm
```

**Comment by frizikk** [comment]
For PhpStorm users and for myself in the future

`flatpak override --user --filesystem=/run/docker.sock com.jetbrains.PhpStorm`

**Comment by nash0rn** [comment]
For PyCharm Community users and for myself in the future

`flatpak override --user --filesystem=/run/docker.sock com.jetbrains.PyCharm-Community`

**Comment by HT-Dat** [comment]
For Rider users and for myself in the future
flatpak override --user --filesystem=/run/docker.sock com.jetbrains.Rider

**Comment by bwplotka** [comment]
This is similar for Goland. Unfortunately override does not work for me as my socket is running under `var/run`.

```
 ~/.bin/docker image ls
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

 Adding this file `/var/run/docker.sock` to `filesystem` section, makes Goland unable to start:

```
flatpak run com.jetbrains.GoLand
bwrap: Can't make symlink at /var/run: File exists
```

**Comment by Job79** [comment]
Are there any downsides to adding `xdg-run/podman` and `xdg-run/docker` by default?

**Comment by x80486** [comment]
Would you be able to test the build from pull request 158 above and provide feedback?

It works fine for me. I had to remove first the manually introduced permissions via `Fatseal`.

**Comment by Spikhalskiy** [comment]
@x80486 
I had to use 

```
sudo flatpak override --filesystem=/run/docker.sock com.jetbrains.IntelliJ-IDEA-Ultimate
```

with Ubuntu 24.04 and a fresh installation of

IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.8.0-31-generic
Registry:
  ide.browser.jcef.sandbox.enable=false
  ide.experimental.ui=true
Non-Bundled Plugins:
  Pythonid (241.14494.314)
Kotlin: 241.14494.240-IJ
Current Desktop: ubuntu:GNOME

**Comment by x80486** [comment]
@Spikhalskiy, I have to do the same. I use Arch Linux, and `--filesystem=xdg-run/docker` does not resolve `/run/docker.sock` correctly. I would have to file an issue in the Flatpak tracker to see what's their input on this.

**Comment by viniciuspinatti** [comment]
@davidparks21 your comment save me. I spent one hour trying to solve it and now it is working!
IntelliJ-IDEA-Ultimate 2024.1.4 (Build #IU-241.18034.62, built on June 20, 2024)
Linux Mint 21.3 Cinnamon
Runtime version: 17.0.11+1-b1207.24 amd64

**Comment by viniciuspinatti** [comment]
I spent one hour trying to solve it and now it is working using the following command

`flatpak override --user --filesystem=/run/docker.sock com.jetbrains.IntelliJ-IDEA-Ultimate`

IntelliJ IDEA Ultimate 2024.1.4 (Build #IU-241.18034.62, built on June 20, 2024)
Linux Mint 21.3 Cinnamon
Runtime version: 17.0.11+1-b1207.24 amd64
Docker version 27.0.3, build 7d4bcd8
