### ISSUE TITLE
Provide update information on breaking changes

### ISSUE THREAD

**Issue by cxrvh** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#226]
The recent permission changes break existing workflows. It would be great to inform us about this with an update message (like first_run.txt & sdk_update.txt) on what has changed & how to revert it.

By mistake, I had auto-update in GNOME Software active. As a result I did not notice these changes.

As a note: I think it would be better if you could limit the number of cleanup updates (meaning pushing to master) since each one requires a full download of the IntelliJ archive.

**Comment by xanscale** [comment]
agree, your breaking change is about permissio lost of "flatpak-spawn" ?

for note: also agree

**Comment by xanscale** [comment]
closing this issue and considering your feedback for future changes

**Comment by x80486** [comment]
I don't fully remember, but I think `org.freedesktop.Flatpak` is used by Docker.

Same for Git LFS — it _was_ not included by default in the Freedesktop SDK.
