### ISSUE TITLE
Update first_run.txt about --talk-name=org.freedesktop.Flatpak

### ISSUE THREAD

**Issue by cxrvh** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#227]
`first_run.txt` suggests using `flatpak-spawn --host` which is not possible in the default configuration.

Although flatpak-spawn hints at `org.freedesktop.Flatpak`, `first_run.txt` should still be more informative on the matter.

**Comment by cardil** [comment]
@cxrvh Consider commenting on the #228. Looks like we should try to convince the maintainer this is worth fixing.

**Comment by xanscale** [comment]
my opinion actually is to mantain without flatpak-spawn

but add more info on first-run.txt about on how to add this permission for who need it
