### ISSUE TITLE
Host's /etc/pki/java/cacerts should be used

### ISSUE THREAD

**Issue by cardil** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#230]
When building with Java, even if I use my own SDK, it still points to in-sandbox `/etc/pki/java/cacerts` file.

This breaks the build, if the cacerts is expected to have additional certs installed (very common in enterprise environments).

For example, on Fedora 41, the file `/usr/lib/jvm/java-21-openjdk-21.0.5.0.11-1.fc41.x86_64/lib/security/cacerts` is a symlink to `/etc/pki/java/cacerts`.

When executing a host's java binary, this symlink points to the in-sandbox `/etc/pki/java/cacerts` file, instead of the host's `/etc/pki/java/cacerts` file.

The in-sandbox `/etc/pki/java/cacerts` file, should be symlinked to the host's `/etc/pki/java/cacerts` file.

**Comment by cardil** [comment]
Maybe the [`host-etc`](https://docs.flatpak.org/en/latest/sandbox-permissions.html) should be used and the `/etc/pki/java/cacerts` should be linked to the `/run/host/etc/pki/java/cacerts`.

The `/etc/pki//java/cacerts -> /etc/pki/ca-trust/extracted/java/cacerts`, so probably we should link `/etc/pki/ca-trust/extracted/java/cacerts -> /run/host/etc/pki/ca-trust/extracted/java/cacerts`

WDYT @xanscale?

**Comment by cardil** [comment]
I need to use custom certificates to connect to some hosts from Maven/Gradle. Even with using bundled JVM this will not work.

**Comment by xanscale** [comment]
understood, i mean you should not thinking about config your host machine but your sandbox or even better your project

somethink like this: https://stackoverflow.com/questions/43483514/how-to-pass-truststore-property-in-gradle-build-script

**Comment by cardil** [comment]
Even if I do something like this (ref.: https://stackoverflow.com/a/43486698/844449) it still points to the in-sandbox `cacerts` file, and build fails. I would need to bundle the _cacerts_ with the projects, which is not an option

```groovy
System.setProperty('javax.net.ssl.trustStore', '/etc/pki/java/cacerts')
System.setProperty('javax.net.ssl.trustStorePassword', 'changeit')
```

**Comment by cardil** [comment]
> @xanscale: `host-etc` seams interesting, can you try using flatseal?

Yes, I see the host's `/etc` directory under `/run/host/etc`:

```sh
$ flatpak run --command=sh com.jetbrains.IntelliJ-IDEA-Ultimate
[📦 com.jetbrains.IntelliJ-IDEA-Ultimate ~]$ ls -la /run/host/etc/pki/ca-trust/extracted/java/cacerts 
-r--r--r--. 1 nfsnobody nfsnobody 170034 Nov  1 18:38 /run/host/etc/pki/ca-trust/extracted/java/cacerts
[📦 com.jetbrains.IntelliJ-IDEA-Ultimate ~]$ ls -la /etc/pki/ca-trust/extracted/java/cacerts 
-rw-r--r--. 7 nfsnobody nfsnobody 164985 Jan  1  1970 /etc/pki/ca-trust/extracted/java/cacerts
```

But, I can't symlink it. That probably needs to be done during the container build:

```sh
[📦 com.jetbrains.IntelliJ-IDEA-Ultimate java]$ mv cacerts cacerts.old
mv: cannot move 'cacerts' to 'cacerts.old': Read-only file system
```

**Comment by xanscale** [comment]
in gradle.properties you can point file located in your home

**Comment by cardil** [comment]
Do you see any reasons why not to link: `/etc/pki/ca-trust/extracted/java/cacerts -> /run/host/etc/pki/ca-trust/extracted/java/cacerts` using `host-etc` permission? 

Personally, I don't see any reasons why not to do it. Even the extensions you have mentioned use the host's cacerts, see: https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk/blob/branch/24.08/extract_cacerts.sh

**Comment by xanscale** [comment]
> Do you see any reasons why not to link: `/etc/pki/ca-trust/extracted/java/cacerts -> /run/host/etc/pki/ca-trust/extracted/java/cacerts` using `host-etc` permission?

none, but not sure it should be done inside this flatpak, it's more on openjdk flatpak ext.

> Personally, I don't see any reasons why not to do it. Even the extensions you have mentioned use the host's cacerts, see: https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk/blob/branch/24.08/extract_cacerts.sh

this is very interesting, but actually not works ? if I understood the code it make more or less what you want. 
so in you use jdk from the extension it actually works, no ?

**Comment by cardil** [comment]
> @xanscale: this is very interesting, but actually not works ? if I understood the code it make more or less what you want. so if you use jdk from the extension it actually works, no ?

It works with JDK from the extension, yes. But, I still think it is a valid issue, as it doesn't work with the built-in JDK.

Moreover, I'd like to avoid the additional 0.5GiB of flatpak SDK, and use various JDKs I have on my host machine, provided by SDKman. Also, IntelliJ has a [download SDK feature](https://www.jetbrains.com/guide/java/tips/download-jdk/) itself. All of this could work nicely if the `cacerts` file is linked to the host's system.

**Comment by xanscale** [comment]
flatpak is intended to works with flatpak runtime and flatpak extensions, not with host software.

flatpak is not the only way to use IDEA, just stop using flatpak or start to use flatpak realy.

**Comment by cardil** [comment]
You shouldn't be telling people what they should do, or not, you know? 

This still breaks with the default configuration, so why you close the issue?!? Just rude behavior!

**Comment by xanscale** [comment]
"This still breaks with the default configuration"

explain please

**Comment by cardil** [comment]
This flathub package `com.jetbrains.IntelliJ-IDEA-Ultimate` contains JDK, which is [delivered with it](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/blob/master/README.md#flatpak-standard-sdk). This JDK doesn't work with custom certificates.

**Comment by xanscale** [comment]
it's intended as basic usage. for advanced usage exists openjdk extension

**Comment by cardil** [comment]
Lol man, you keep telling people what is the "right" way of using software! Way to go!

**Comment by xanscale** [comment]
it's not even a standard openjdk but the custom version by jetbrain to run the IDE.

**Comment by cardil** [comment]
I opened the issue, and was considering opening a PR, to help this project, especially with adoption, making it easier to use it.

Now, I clearly see, it's not worth it. Toxic thinking on your side.

**Comment by xanscale** [comment]
i'm  just no agree with you. a flatpak standard solution already exists and works
