### ISSUE TITLE
EXTRA_PATH should be appended to path, not prepended

### ISSUE THREAD

**Issue by muelli** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#29]
https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/commit/cfed777883b2e867649cbc66c2554aa68563aed0 has re-ordered the `EXTRA_PATH`. Was that on purpose? It breaks the app for me, because trivial things like git cannot be executed.

**Comment by TingPing** [comment]
Its almost like its a conceptually broken idea...

**Comment by x80486** [comment]
I can do that, not a big deal, but do you mind explaining really quick how's that breaking the application for you?

---

On the other hand, `Git` must be available to you with no effort. I guess you won't be able to do a few things, like signing commits, etc., but it should be OK for the most part:

```shell
[x80486@uplink essentials]$ whereis git
git: /usr/bin/git /nix/store/dzpxi8vx0xjw77gnva8lsjl52vzn5fqs-user-environment/bin/git
[x80486@uplink essentials]$ /usr/bin/git --version
git version 2.21.0
[x80486@uplink essentials]$ git --version
git version 2.22.0
```

Version `2.21.0` is provided by the Flatpak (I think it's because the `"runtime": "org.freedesktop.Sdk"`) and version `2.22.0` is my system's version.

**Comment by TingPing** [comment]
They use this to use host binaries, host binaries are broken, so tada. If the host binaries are second in the list its only half broken.

**Comment by muelli** [comment]
yes. Prepending host binaries results in havoc. For me, executing git from the host results in:
```
$ /run/host/usr/bin/git
/run/host/usr/bin/git: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory
$
```

As I've mentioned in my commit message https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/commit/fd85a680f59fc6657b315bf1d5794cdb94d35b69 it's surprising that it breaks. But by prepending the extra path breakage is much more likely.

**Comment by x80486** [comment]
...all right, I'm going to alter the order for that folk, but this is probably one of those things that can turn into a sweet nightmare and we're going to have a hard time to rollback if people get used to it.

The only (non-super-optimal) solution I've found for this is just to have your stuff installed in your home directory. You won't need any of this Jiu Jitsu for the most part...just a tip!

**Comment by x80486** [comment]
Hey @muelli, are you OK with this one or do you need something else?

**Comment by muelli** [comment]
Ah, there has been a change with https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/commit/dbb6994fdaa6bf4e5caa5cf3ee40ae9aa7055471 (I don't even remember having written that patch..).  Yeah, it's certainly better now than before.
