### ISSUE TITLE
Backticks not working

### ISSUE THREAD

**Issue by BjoernDaase** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#30]
Version: 2019.2.0  
OS: Fedora Rawhide  

It seems like backticks are not working properly. Normally you would e.g. create a é, by first pressing <kbd>´</kbd> followed by pressing <kbd>e</kbd>. Also inserting a backtick only (<kbd>´</kbd> followed by another <kbd>`</kbd>) does not work.  
It works perfectly fine in the Host OS.

**Comment by x80486** [comment]
What keyboard layout are you using in order to create those _glyphs_? I just happen to speak Spanish, so I do a lot of what you are stating and so far I have no issues, of course, provided I have the correct layout (or input source) in order to create those glyphs.

![image](https://user-images.githubusercontent.com/34633617/62979487-eea3f000-bdf1-11e9-8b84-11115de57b8f.png)

I also tested this on Linux Mint and Ubuntu `19.x`...and no issues so far.

**Comment by BjoernDaase** [comment]
Hmm, weird. I use a German keyboard layout....

**Comment by x80486** [comment]
I would say, install any other Flatpaks (`WebStorm`, `IntelliJ Community`, `gedit`) and see if you have the same issue(s).

**Comment by BjoernDaase** [comment]
I did some testing today. The problem appears in all tested JetBrains Flatpaks (Intellij Pro, IntelliJ Community, Pycharm) but not in other Flatapk apps (gedit).

**Comment by BjoernDaase** [comment]
Edit: I did not mention it in the original post but backticks also work fine in the snap version.

**Comment by x80486** [comment]
@BjoernDaase, can you try the just released `2019.2.3` version? They updated/rebased the runtime and did some other (probably unrelated) changes.

In any case, I think this is an issue with Fedora Rawhie (and probably the Flatpak version that comes with it). I've tested several times in some other distros and it's OK. If you have a chance try to test the same Flatpak in another distro and see if you have the same issue(s).

**Comment by BjoernDaase** [comment]
@x80486 I wanted to test it today, but intellij does not start anymore:

```
Picked up JAVA_TOOL_OPTIONS: -Djava.io.tmpdir=/home/bjoern/.var/app/com.jetbrains.IntelliJ-IDEA-Ultimate/cache/tmp/
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Error: Could not find or load main class E
Caused by: java.lang.ClassNotFoundException: E
```

But the snap also does not start anymore since 2019.2.3, so it is definitely not a flatpak fault. I will try again when this issue is resolved.

**Comment by x80486** [comment]
It must start. I just tested it in `Arch Linux`, `Ubuntu`, `openSUSE Tumbleweed`, and `Fedora Silverblue`:

```shell
[x80486@uplink ~]$ flatpak run com.jetbrains.IntelliJ-IDEA-Ultimate 
Picked up JAVA_TOOL_OPTIONS: -Djava.io.tmpdir=/home/x80486/.var/app/com.jetbrains.IntelliJ-IDEA-Ultimate/cache/tmp/
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.ide.ClassUtilCore to field sun.net.www.protocol.jar.JarFileFactory.fileCache
WARNING: Please consider reporting this to the maintainers of com.intellij.ide.ClassUtilCore
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Gtk-Message: 20:09:17.061: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:09:17.061: Failed to load module "canberra-gtk-module"
```

Are you still in `Rawhide`? Would be nice if you can test on some other distro.

**Comment by BjoernDaase** [comment]
@x80486 Sorry for not coming back to you in time. I simply had not time to return to this problem.

> Are you still in Rawhide? Would be nice if you can test on some other distro.

I am on Fedora 31 now.

> It must start. I just tested it in Arch Linux, Ubuntu, openSUSE Tumbleweed, and Fedora Silverblue:
> [x80486@uplink ~]$ flatpak run com.jetbrains.IntelliJ-IDEA-Ultimate 
> Picked up JAVA_TOOL_OPTIONS: -Djava.io.tmpdir=/home/x80486/.var/app/com.jetbrains.IntelliJ-IDEA-Ultimate/cache/tmp/
> OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.intellij.ide.ClassUtilCore to field sun.net.www.protocol.jar.JarFileFactory.fileCache
> WARNING: Please consider reporting this to the maintainers of com.intellij.ide.ClassUtilCore
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> Gtk-Message: 20:09:17.061: Failed to load module "canberra-gtk-module"
> Gtk-Message: 20:09:17.061: Failed to load module "canberra-gtk-module"

First of all, I fixed the non-starting IntelliJ. That was simply due to some malicious IntelliJ config (`$HOME/.IntelliJIdea2019.2`). After deleting that, IntelliJ started just fine again.

To come back to the original problem with the dead keys. After some investigation I narrowed down the problem to my current specific user account. Backticks indeed work fine, when:
* Running `flatpak run com.jetbrains.IntelliJ-IDEA-Ultimate` as `root`
* Create a new user and run  `flatpak run com.jetbrains.IntelliJ-IDEA-Ultimate`
* Use a F31, F Rawhide or Manajro VM and run  `flatpak run com.jetbrains.IntelliJ-IDEA-Ultimate`

So, it seems to be indeed no problem with the IntelliJ flatpak in general, so if you wish feel free to close this issue.

Anyway, I obviously wanted to fix the problem. I tried the following steps:
* Delete `$HOME/.IntelliJIdea2019.2`
* Reinstall `com.jetbrains.IntelliJ-IDEA-Ultimate` flatpak
* Delete `$HOME/.var`
* Reinstall `flatpak`
* Delete `$HOME/.cache`, `$HOME/.ccache`, `$HOME/.local`, `$HOME/.config`, `$HOME/.java`

Unfortunately, none of the steps above help. Backticks still do not work for my specific user account. Do you have any idea or input you could give me to fix this problem (without reinstalling my PC)?

Cheers in advance and keep up the good work :)

**Comment by x80486** [comment]
I don't think I can give you any pointers. I would delete the user and create a new one; also it could be that you have some issue with the Java applications in general, or even more specifically the IntelliJ runtime, but that's weird also because you said that the Snap package works fine, so it's something that you have and these IntelliJ packages.

I wish I can have any other ideas, but it's very specific. If I can think of something else I'll write something here :sunglasses:

**Comment by BjoernDaase** [comment]
Hmm, yeah,you are probably right. But unfortunately that is some serious pain...

**Comment by hfluz** [comment]
I'm also affected by this issue. I use pt_BR keyboard layout on Fedora 31 (so it seems it's related to this distro). This doesn't happen if it's installed through Jetbrains Toolbox.

**Comment by BjoernDaase** [comment]
> I'm also affected by this issue. I use pt_BR keyboard layout on Fedora 31 (so it seems it's related to this distro). This doesn't happen if it's installed through Jetbrains Toolbox.

Does the workaround to launch IntelliJ as another users (e. g. root) also work for you?

**Comment by hfluz** [comment]
No, I didn't try that, but I already formatted my Fedora partition and installed Arch Linux because I was having other issues besides this one.

I still have Fedora 31 in my home computer, but here Intellij works fine through flatpak. In my work computer, I had installed IntelliJ through Toolbox before installing the flatpak version, so maybe my config folder was messed up.

**Comment by BjoernDaase** [comment]
It is like definitely ultra weird.  
But could you think of any more config folders than the ones I listed in https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/issues/30#issuecomment-549073225?

**Comment by hfluz** [comment]
> But could you think of any more config folders than the ones I listed in [#30 (comment)](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/issues/30#issuecomment-549073225)?

Unfortunately I can't, but I wasn't able to think anything else I did different between my home and my work computers.

**Comment by BjoernDaase** [comment]
So, I finally found to reinstall my OS --> problem is gone!

**Comment by x80486** [comment]
All right; feel free to open up this one again if something "shows up" for this.

**Comment by hidalgob** [comment]
This is also happening to me. I can't type any "accent" in the editor.
For example "`" (backtick) or "é"
I'm running on CentOs 7 pt-BR keyboard. I have no issues typing it anywhere else. 
Installed Idea Community through the Jetbrains toolbox. 
Also updated to version to the last version of 2019.3.2 and the issue persists.

**Comment by RafRunner** [comment]
Just to remind that this is still a issue. Using:
Pop!_OS 20.04
Gnome 3.36.3
Kernel: 5.4.0-7642-generic
IntelliJ version: 2020.2.3
Flatpak 1.6.5
Using pt-BR default keyboard (with dead keys) none of the dead keys work

output from ~$ set | grep -E 'XMODIFIERS|GTK_IM_MODULE|QT_IM_MODULE';setxkbmap -query:
GTK_IM_MODULE=ibus
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
rules:      evdev
model:      pc105
layout:     br,us
variant:    ,

My way to work around the issue was to install snapd and install the snap package (what is not optimal) but the snap version works 100% fine with no configuration needed
