### ISSUE TITLE
Can't pull via SSH auth if gpg-agent is set as ssh-agent

### ISSUE THREAD

**Issue by taaem** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#34]
I'm using my gpg-agent to authenticate ssh via gpg, so I can use a smartcard for my private keys. (https://wiki.archlinux.org/index.php/GnuPG#SSH_agent) 
The problem is that the socket gpg-agent uses (/run/user/....) is not accessible inside the flatpak, is there a way to allow access to that socket to this flatpak somehow?

**Comment by taaem** [comment]
I can push and pull via gitg installed in a flatpak so I assume its possible.
Also I just looked at that packaging and it seems this is fixable by adding the ssh-socket to the application: https://github.com/flathub/org.gnome.gitg/blob/master/org.gnome.gitg.json#L15
```
        /* Required fot push action */        
        "--socket=ssh-auth",
        /* We need access to auth agents */
        "--talk-name=org.freedesktop.secrets",
        "--filesystem=xdg-run/keyring"
```

**Comment by x80486** [comment]
I don't fully understand what's the issue.

Are you able to use Git over SSH? Or that's OK and you cannot sign commits (and etcetera) using GnuPG?

**Comment by taaem** [comment]
Ah sorry I probably wasn't clear, I can't git push/pull via ssh public key authentication, because I'm using a gpg key as ssh key and the socket for the agent is not exposed to the flatpak, so the authentication fails.
Maybe this time its clearer.

**Comment by x80486** [comment]
I can definitely add `--socket=ssh-auth`, and that would let you use `Git` over SSH, but as far as I know, there is no way to "talk to" the `GnuPG` agent for now within the Flatpak, so signing commits won't work.

If that's not what you meant, you can try giving me the `Git` commands you are trying to use, in that way probably I understand what you meant by _using a gpg key as ssh key_ and so on – I'm not versed at all on the GPG arena.

**Comment by taaem** [comment]
For me the ssh-agent should be enough. That should enable me to do what I want :smile:

**Comment by x80486** [comment]
OK, let's add it then! I know it was going to be needed, but I never remembered to add it between releases. Hold on tight because I'm also upgrading to Freedesktop `19.08` :wink:

**Comment by taaem** [comment]
Many thanks!

**Comment by x80486** [comment]
@taaem, give it a shot to the just released `2019.2.3` version; it will come by default with `--socket=ssh-auth` and `--filesystem=xdg-run/keyring` added/enabled/set.

**Comment by taaem** [comment]
Thanks! 
Pulling and pushing works but now after startup I got:

> Native Keychain not available
> In-memory password storage will be used.

which is probably related to `--filesystem=xdg-run/keyring` it doesn't bother me since I don't use any passwords, but just wanted to let you know.

**Comment by x80486** [comment]
I know what's that :rofl:

I removed `libsecret` because it didn't build with Freedesktop `19.08`, once that's sorted out, I'll put it back and you will be OK in that matter.
