### ISSUE TITLE
Release 2019.3.4

### ISSUE THREAD

**Issue by cxrvh** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#44]
The last update was never released.

    flatpak remote-info flathub --log com.jetbrains.IntelliJ-IDEA-Ultimate
    
    IntelliJ IDEA Ultimate - Capable and Ergonomic Java IDE for Enterprise, Web and
    Mobile Development
    
            ID: com.jetbrains.IntelliJ-IDEA-Ultimate
           Ref: app/com.jetbrains.IntelliJ-IDEA-Ultimate/x86_64/stable
          Arch: x86_64
        Branch: stable
       Version: 2019.3.3
       License: LicenseRef-proprietary
    Collection: org.flathub.Stable
      Download: 215.7?kB
     Installed: 562.2?kB
       Runtime: org.freedesktop.Sdk/x86_64/19.08
    
           Sdk: org.freedesktop.Sdk/x86_64/19.08
        Commit: 55db711614e7faa7e36275dffe8e4c06d278dc6802f0f61b1efc4b8661ee068a
        Parent: fde28412c36204893cc4d00fa215461f697bab028918a15be2db0c447252579c
       Subject: intellij idea ultimate edition release 2019.3.3 (b88e93b9)
          Date: 2020-02-11 15:58:27 +0000
       History: 
    
        Commit: fde28412c36204893cc4d00fa215461f697bab028918a15be2db0c447252579c
       Subject: use libsecret from shared-modules (9af1fd58)
          Date: 2020-01-23 11:52:40 +0000

**Comment by x80486** [comment]
Indeed...that rarely happens.

I just scheduled a build :rocket: ...should be available any time soon.
