### ISSUE TITLE
Can't remember passwords

### ISSUE THREAD

**Issue by taaem** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#46]
Flatpacked Idea can't remember passwords for eg. databases, even though I choose to remember the password after a restart I get asked again.

This is probably due to some `secrets` or `gnome-keyring` API not available inside the sandbox. I think maybe a permission to `org.freedesktop.secrets` or something along the lines needs to be added.

Best Regards

**Comment by x80486** [comment]
@taaem, that works as expected, as far as I can tell. I use it every day. What database are you using? I use MariaDB, MySQL and PostgreSQL, not sure if the behaviour is different with others, but it shouldn't – it should use the native keychain, and the Flatpak has already `--talk-name=org.freedesktop.secrets` and `--filesystem=xdg-run/keyring`.

Make sure you are saying: save the password _forever_ inside IntelliJ? Also, what operating system are you using? I can install it and test on it.

**Comment by taaem** [comment]
I'm using MariaDB on my host. I definitely save it forever, and I'm using Fedora 32, but I had the issue on Fedora 31 too.
But you're right the permissions are there.

**Comment by x80486** [comment]
OK, let me try Fedora `32` (I would assume it's not Silverblue)...will let you know.

**Comment by taaem** [comment]
No I'm not using Silverblue

**Comment by x80486** [comment]
Yeah, well...this one is going to get tricky, but I think it might be a problem with something in your system; I've tried in Arch Linux, Ubuntu LTS and Fedora `32` (beta) and it works fine.

Is there anything in the IDE logs "telling" something interesting?

Would you mind trying DataGrip?

**Comment by taaem** [comment]
DataGrip works fine, maybe I should remove my settings and all app data for IDEA? Do you think that would maybe fix the issue?

In the IDE logs is nothing interesting.

**Comment by x80486** [comment]
They both work exactly the same way in the sense both come from the same "base", so that's what I thought it would happen; there are high chances it's a problem isolated to your system and/or IntelliJ IDEA install.

You can put aside the settings in `${HOME}/.var/app/com.jetbrains.IntelliJ-IDEA-Ultimate/` (assuming you are in version `2020.x`, otherwise look into your home directory for `.IntelliJYYYY.X/`), jank it and start again.

**Comment by taaem** [comment]
Okay removing all settings fixed it for me, maybe it was time for clean setup :shrug:
