### ISSUE TITLE
Problem with working on the terminal/Git with my SSH config

### ISSUE THREAD

**Issue by petarlishov** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#48]
I have set up SSH with some configurations for Kerberos . My SSH config file looks like this:
```
Host *.somethingsomething.whatever
	User herpaderp
	GSSAPIAuthentication yes
	GSSAPIKeyExchange yes
	GSSAPIDelegateCredentials yes
	ForwardAgent yes
```
I do not want to use Kerberos in the terminal of IntelliJ, but I need to be able to git fetch, pull, push and others to GitHub. When I attempt to use the Git integration or the terminal for the task, I am returned this error:
```
sh-5.0$ git fetch
/home/petarlishov/.ssh/config line 5: Unsupported option "gssapiauthentication"
/home/petarlishov/.ssh/config: line 7: Bad configuration option: gssapikeyexchange
/home/petarlishov/.ssh/config line 9: Unsupported option "gssapidelegatecredentials"
/home/petarlishov/.ssh/config: terminating, 1 bad configuration options
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by x80486** [comment]
Check two things:

- Your OpenSSH / OpenSSL version in the host – your Linux's `Terminal` application
- Your OpenSSH / OpenSSL version within the Flatpak – the embedded Terminal in IntelliJ IDEA

They must be different, being the one within the Flatpak way more recent, hence some crypto features may have been deprecated. I tried your options and I got the same errors/warnings in Arch Linux.

Being said that, I would always recommend to switch to your "real shell" when you open up the IntelliJ IDEA terminal, some times is just pure placebo, but I've seen that other times it behaves (a little bit) better... still, the integration between that and the operating system's shell is years light away.

**Comment by petarlishov** [comment]
Yeah thanks for helping with this. I have moved away from using Flatpak for development tools. I believe you were right about the versions being different, but I encountered other problems as well. I am sure they can be solved but I believe you have to fully commit to learning Flatpak.
