### ISSUE TITLE
Let intellij update itself

### ISSUE THREAD

**Issue by peey** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#52]
![image](https://user-images.githubusercontent.com/4688870/86895741-8d2ff280-c122-11ea-905b-223e8297e13c.png)

The "update and restart" button should become available. I suppose that updating entire flathub image might incur more downloads than the in-app update.

**Comment by x80486** [comment]
If you are using the Flatpak version you should be using `flatpak update` (or something similar) to update your Flatpaks.

There are very few applications that, once packaged in such way (Flatpak, Snap, etc.), will let you do in-place updates.

**Comment by peey** [comment]
> There are very few applications that, once packaged in such way (Flatpak, Snap, etc.), will let you do in-place updates.

I agree, but since intellij seems to have the option, I'm suggesting you allow it.

I'm not sure how significant the difference is, but I think it might require less download overhead.

**Comment by x80486** [comment]
They write into the application's sub-directory, not outside of it — like any of the XDG sub-directories that it creates. The Flatpak container is read-only, what you are asking is impossible **unless they change the path** where they place the updates.

You can create a ticket in their [bug and issue tracker](https://youtrack.jetbrains.com/issues/IDEA/) for this to be considered; once that's implemented you can have differential updates in such way.

**Comment by peey** [comment]
Got it. I didn't know that that directory was read-only. Thanks!
