### ISSUE TITLE
About the Toolbox Flatpak

### ISSUE THREAD

**Issue by Khyber3737** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#53]
Hi @x80486 I've read your comment about the Jetbrains Toolbox Flatpak. If you already know this feel free to just close the issue! Here's how to make it work since they moved to Kotlin.

APPDIR is required. AppRun is the executable. I don't know how to make a Flatpak correctly but hey it works.

```
"shared-modules/glu/glu-9.json",
"shared-modules/gudev/gudev.json",
"shared-modules/gtk2/gtk2.json",

{
  "name": "jetbrains-toolbox",
  "buildsystem": "simple",
  "build-commands": [
    "mkdir -p /app/bin",
    "tar xvf jetbrains-toolbox-*.tar.gz",
    "rm jetbrains-toolbox-*.tar.gz",
    "jetbrains-toolbox-*/jetbrains-toolbox --appimage-extract",
    "mv squashfs-root/* /app/bin",
    "rm -rf squashfs-root",
    "chmod 0755 /app/bin/AppRun",
    "chmod 0755 /app/bin/jetbrains-toolbox",
    "chmod 0755 /app/bin/jetbrains-toolbox-helper"
  ],
  "sources": [
    {
      "type": "file",
      "url": "https://download.jetbrains.com/toolbox/jetbrains-toolbox-..........tar.gz",
      "sha256": "..................."
    }
  ]
}
```

```
LD_LIBRARY_PATH=/app/bin:$LD_LIBRARY_PATH
APPDIR=/app/bin
```

**Comment by x80486** [comment]
Hi @Khyber3737, I [started something similar](https://github.com/x80486/flathub/tree/com.jetbrains.toolbox/) but then I realized they are packaging the Toolbox as an AppImage. Extracting the contents and repackaging is not really a nice approach because that's a binary — if it would be a JAR the story would be different.

I put the comment on their issue tracker. If they open source the application or package it slightly different I can create the Flatpak for it.

**Comment by Khyber3737** [comment]
To me _in practice_ the end result looks like any other extractable format, binary yes, but I understand. Because once you put trust in JetBrains and their servers/apps you're doing the same kind of operations once you run Toolbox, it's the primary usage of the application. Downloading their binary apps, extracting and executing them.
Let's hope they move to a regular tar file, would be nice to have Toolbox managing everything.

**Comment by refi64** [comment]
Worth noting that there are several Flatpaks that use an Appimage as their source, e.g. Unity Hub.
