### ISSUE TITLE
Place /run/host/usr/bin on PATH?

### ISSUE THREAD

**Issue by devurandom** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#6]
Would it be possible to place `/run/host/usr/bin` on the `PATH`, so that the host's binaries would be available in the container? Then you would not have to bundle `git`, `hg`, `ssh` and so on.

See-Also: https://youtrack.jetbrains.com/issue/IDEA-189485#focus=streamItem-27-3238075-0-0

**Comment by TingPing** [comment]
No. Most things there won't run.

**Comment by devurandom** [comment]
Is there another way to allow unbundling of all those binaries? x80486 mentioned something about SDK extensions?

**Comment by x80486** [comment]
If `git` becomes a problem I will bundle it and it would be accessible in `/app/bin/git`, as it's done with many other Flatpaks — I never use the Git plug-in from IntelliJ IDEA though.

And yes, as TingPing said, placing `/run/host/usr/bin` on the `PATH` wouldn't work. The way I go around those issues is by installing all that stuff in my home directory using `Nix Packages` — just another "option".

**Comment by devurandom** [comment]
> The way I go around those issues is by installing all that stuff in my home directory using `Nix Packages` — just another "option".

That does not really appear to be satisfying, since it would mean that I would have to package lots of packages that are already present on the host also in `~/.local`. I use Flatpak primarily for binary packages from third party vendors, which are not available via my distribution or not available in a current version. Hence most of my software will reside on the host, supplied by my distribution, not in my home directory.

**Comment by TingPing** [comment]
`git` is already in `org.freedesktop.Sdk` which this should be using. So that is that solved.

**Comment by TingPing** [comment]
Anyway there was an idea to make a generic extension point for dev tools that all Flatpak'd IDEs use. I don't have the time do to this but if somebody wants to step up stop by #flatpak and we can discuss it.
