### ISSUE TITLE
The size miss match with 2020.3.3

### ISSUE THREAD

**Issue by netroby** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#69]
Error: Wrong size for extra data https://download.jetbrains.com/idea/ideaIU-2020.3.3.tar.gz
error: Failed to install com.jetbrains.IntelliJ-IDEA-Ultimate: Wrong size for extra data https://download.jetbrains.com/idea/ideaIU-2020.3.3.tar.gz

so failed to install

**Comment by x80486** [comment]
This is quite the thing. I've seen this a couple of times already. Looks like the file was changed or something.

Let me check those again...

**Comment by x80486** [comment]
OK, probably what you've got was a temporary problem:

```shell
[x80486@ubuntu-vm:~]$ flatpak install flathub com.jetbrains.IntelliJ-IDEA-Ultimate 
Looking for matches…
Remote ‘flathub’ found in multiple installations:

   1) system
   2) user

Which do you want to use (0 to abort)? [0-2]: 2

com.jetbrains.IntelliJ-IDEA-Ultimate permissions:
    ipc                  network      ssh-auth      wayland      x11      dri      file access [1]
    dbus access [2]

    [1] host, xdg-run/keyring
    [2] org.freedesktop.Flatpak, org.freedesktop.Notifications, org.freedesktop.secrets


        ID                                              Branch            Op           Remote            Download
 1. [✓] org.freedesktop.Platform.GL.default             20.08             u            flathub            95.9 MB / 95.9 MB
 2. [✓] org.freedesktop.Sdk.Locale                      20.08             u            flathub            17.6 kB / 326.7 MB
 3. [✓] org.freedesktop.Sdk                             20.08             u            flathub           371.0 MB / 564.1 MB
 4. [✓] com.jetbrains.IntelliJ-IDEA-Ultimate            stable            i            flathub           152.3 kB / 872.4 MB

Changes complete.
```

I was able to install this version, and the file matches what's in the [manifest](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/blob/df0e7c2d1805ac7f833bb392af28e538d23dce3b/com.jetbrains.IntelliJ-IDEA-Ultimate.yml#L32):

```shell
[x80486@ubuntu-vm:~/Downloads]$ sha256sum ideaIU-2020.3.3.tar.gz 
e7dbca1cbc34da19da4f58df44f599c128317a692dea8ac3977e594b36760baf  ideaIU-2020.3.3.tar.gz
[x80486@ubuntu-vm:~/Downloads]$ stat ideaIU-2020.3.3.tar.gz 
  File: ideaIU-2020.3.3.tar.gz
  Size: 872140391 	Blocks: 1703408    IO Block: 4096   regular file
Device: 10303h/66307d	Inode: 9712438     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/   gorre)   Gid: (  985/   users)
Access: 2021-03-26 08:26:49.159506729 -0400
Modify: 2021-03-26 08:26:27.519719557 -0400
Change: 2021-03-26 08:26:27.899715755 -0400
 Birth: 2021-03-26 08:25:49.960107089 -0400
```

**Comment by netroby** [comment]
![image](https://user-images.githubusercontent.com/66301650/112697383-5e30fb00-8ec2-11eb-8e64-471620069a17.png)
You have a local cache?

**Comment by netroby** [comment]
![image](https://user-images.githubusercontent.com/66301650/112697400-6852f980-8ec2-11eb-970e-7f468237232e.png)
What i fresh download file size was 872.1MB, and the need to download file size was 872.4MB
It seems different.

**Comment by x80486** [comment]
I don't have a cache because I use a VM for testing these stuff, but even so, if the process is borked, no cache will help you since the data would be corrupt.

It's really strange you get that consistently. What OS are you using?

**Comment by netroby** [comment]
Linuxmint 20.1 x86_64

I also tried the PHPStorm , it works.

**Comment by netroby** [comment]
I am try to download the file by manual.

```
$ aria2c https://download.jetbrains.com/idea/ideaIU-2020.3.3.tar.gz

03/27 09:54:09 [NOTICE] Downloading 1 item(s)
[#5c59bc 0B/0B CN:1 DL:0B]
03/27 09:54:11 [NOTICE] CUID#7 - Redirecting to https://download.jetbrains.8686c.com/idea/ideaIU-2020.3.3.tar.gz
[#5c59bc 28MiB/831MiB(3%) CN:1 DL:0.9MiB ETA:13m27s]
```

**Comment by netroby** [comment]
```
$ sudo flatpak install phpstorm
Looking for matches…
Found similar ref(s) for ‘phpstorm’ in remote ‘flathub’ (system).
Use this remote? [Y/n]: y
Found ref ‘app/com.jetbrains.PhpStorm/x86_64/stable’ in remote ‘flathub’ (system).
Use this ref? [Y/n]: y

com.jetbrains.PhpStorm permissions:
    ipc    network    ssh-auth    x11    dri    file access [1]    dbus access [2]    tags [3]

    [1] home, xdg-run/keyring
    [2] org.freedesktop.Flatpak, org.freedesktop.Notifications, org.freedesktop.secrets
    [3] proprietary


        ID                              Branch          Op          Remote          Download
 1. [✓] com.jetbrains.PhpStorm          stable          i           flathub         467.9 MB / 468.0 MB

Installation complete.
```
phpstorm install success

**Comment by netroby** [comment]
![image](https://user-images.githubusercontent.com/66301650/112707751-92b7ad80-8ee8-11eb-80ea-b828eacee134.png)

The downloaded idea tar.gz can be untar. 

The sha256sum was :

```
$ sha256sum ideaIU-2020.3.3.tar.gz
^[513920ad1890a9c8325f638f41cca618240cc96a4cb85d8ea26470b0e68bd850  ideaIU-2020.3.3.tar.gz
```

**Comment by x80486** [comment]
Just for the record, I installed this again on another (clean) VM — no problems whatsoever.

I'm not sure if there could be a mirror based on your location or something around those lines, but looks like it might be a problem isolated because I haven't seen anyone else reporting this.

**Comment by njmdietrich** [comment]
I am having the same issue trying to download 2021.1.3, I am also on linux mint so maybe it is somehow related to that?

**Comment by x80486** [comment]
The file/release changed; you can see the next pull request is going to be the third one for this last release — I don't know what keep changing for these releases. Also, I think JetBrains should just increase the `patch` version to reflect the real changes instead of changing the file in place.
