### ISSUE TITLE
Use host's JVM to run IntelliJ?

### ISSUE THREAD

**Issue by devurandom** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#7]
Would it be possible to run IntelliJ on the host's JVM, in order to save me the huge download?

See-Also: https://youtrack.jetbrains.com/issue/IDEA-189485#focus=streamItem-27-3238075-0-0

**Comment by TingPing** [comment]
No.

**Comment by devurandom** [comment]
@TingPing Could you please expand a little on that answer, so that I have a chance to understand?

**Comment by x80486** [comment]
This on its own is close to impossible; moreover, there are certain guarantees you can't satisfy if you do such a thing.

I get that you might have been using the non-JRE bundle for a while, but there will be that one time (and some others to come) that the artifact is not going to work, and that's what the bundled-JRE is satisfying. So you trade off space for that, and make sure that the artifact is going to work regardless of the environment.

**Comment by devurandom** [comment]
> This on its own is close to impossible; moreover, there are certain guarantees you can't satisfy if you do such a thing.

What guarantees are there (made by whom to whom?) that the JVM cannot satisfy?

> I get that you might have been using the non-JRE bundle for a while, but there will be that one time (and some others to come) that the artifact is not going to work, and that's what the bundled-JRE is satisfying. So you trade off space for that, and make sure that the artifact is going to work regardless of the environment.

"artifact" refers to the IntelliJ Java bytecode binary / JAR?

I thought the whole concept of Java is that it runs anywhere there is a JVM? I.e. Java binaries should always be independent of the host system, and instead solely depend on the JVM they run on?

**Comment by TingPing** [comment]
It goes against the entire concept of Flatpak. It is its own self-contained private platform. A host application executing data shipped from a Flatpak, while theoretically possible, is both beyond the scope of Flatpak and against its core design.
