### ISSUE TITLE
Command to grant access to launch Chrome / other Browser

### ISSUE THREAD

**Issue by mattlong-finocomp** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#75]
When opening a html file such as a JUnit generated test-report the IDE shows an overlay of browsers to open the file in.
None of these will launch when clicked. I assume this is because of flatpak sandbox permissions.
Interestingly if you right click the file in the Project browser and select Open In -> Default Browser, then it will launch.
I've tried adding a filesystem override for the google-chrome binary (/usr/bin/google-chrome) but this didn't allow chrome to launch.

In a legacy project we use Karma to run tests and it attempts to launch Chrome via a CHROME_BIN env variable. Running from CLI this works find but within IntelliJ it says that the environment variable isn't set.

**Comment by x80486** [comment]
This is working again for me. Please reopen if that's not the case.
