### ISSUE TITLE
Allow IntelliJ to automatically pick up host's JDKs for projects?

### ISSUE THREAD

**Issue by devurandom** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#8]
Would it be possible to setup container in such a way that IntelliJ would automatically pick up the host's JDK for projects?
* I had to add a new System JDK stored at `/run/host/usr/lib/jvm/java-11-{long version string}`, which was slightly annoying.
* I am using Fedora on the host, which uses `/etc/alternatives` to select the default Java 11 JDK (which on the host allows me to skip the `{long version string}`) – is it possible to somehow make this transparent to IntelliJ?

See-Also: https://youtrack.jetbrains.com/issue/IDEA-189485#focus=streamItem-27-3238075-0-0

**Comment by devurandom** [comment]
> Alternatively, you can install one of the available Sdk Extensions from Flathub and (once restarted the IDE) the SDK should be "visible" in `/usr/lib/sdk/`.

Is there a way to make that a little bit more "automatic"? E.g. when installing the IntelliJ Flatpak, mention that "this program could optionally make use of the following SDK extensions" and offer to also download those?

**Comment by devurandom** [comment]
> I believe that's not going to be possible to do on my side. The JetBrains folks (which I don't work at, for the record) is willing to make those changes on the setup wizard(s) themselves.

I thought maybe Flatpak had a mechanism similar to Debian's recommendations (Debian packages can carry names of "recommended" other packages in their metadata, that enhance or improve this package).

Is it actually possible for an IntelliJ binary running in a Flatpak container to make the host install additional Flatpaks, e.g. the SDK extensions? My assumption was that this would have to happen before starting the Flatpak container, and that it could only happen from the host, not from the container.

**Comment by devurandom** [comment]
> Alternatively, you can install one of the available Sdk Extensions from Flathub and (once restarted the IDE) the SDK should be "visible" in `/usr/lib/sdk/`.

I installed `org.freedesktop.Sdk.Extension.openjdk11/x86_64/18.08`, which I was then able to find in the Flatpak container in `/usr/lib/sdk/openjdk11/jvm/openjdk-11`.

> I believe that's not going to be possible to do on my side. The JetBrains folks (which I don't work at, for the record) is willing to make those changes on the setup wizard(s) themselves.

Are those "changes to the setup wizard(s)" meant to automatically find the JDK in `/usr/lib/sdk/...`? If yes, that would indeed be a good first step towards a user friendly integration with Flatpak SDKs.

**Comment by Zlopez** [comment]
Couldn't `org.freedesktop.Sdk.Extension.openjdk` be required runtime for this flatpak?

This will at least allow user to add some version of java from start.

**Comment by x80486** [comment]
From version `2020.1` IntelliJ IDEA will let you download the Java SDK (almost) of your preference, and place it under `${HOME}/.jdks/`.

By the way, this is exactly the same behavior that `asdf` or SDKMAN does, but without _versioning_.
