### ISSUE TITLE
Missing documentation on how to install / use

### ISSUE THREAD

**Issue by luxalpa** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#90]
So, I tried to use this flatpak thing. Granted, I don't have any experience with flatpak and had to check out how it actually works which is already a pretty bad waste of time. But I'm sure even if I had experience using this, I would find it annoying having to discover every issue by surprise, then having to google the solution. That's not fun and makes usage very unreliable. Personally, I'm just going to uninstall it for now given that flatpak clearly isn't ready yet for real world use.

What this needs to have is a documention about what the user needs to do. It's fairly easy to install this from flathub, but it can not actually be used, since I usually use my development IDE in order to develop things, and it seems none of the SDKs work out of the box (really, nothing works). I managed to get golang to work (partially) by stupidly ticking all the Filesystem subsets in Flatseal (without knowing what I'm doing), but it still can't find docker and docker-compose, and I haven't even tried nodejs, yarn, prettier or git yet.
At this point this looks like a rabbit hole that is going to take me multiple days to go through, and it seems like there's multiple possible solutions with their own drawbacks for each and every one of those issues. For real world usage it shouldn't take more than 5 minutes to setup, so please document what needs to be done in order to get this tool working. I've been spending 3 hours on this now and that's enough productivity / money lost for me to give it up.

**Comment by x80486** [comment]
You need to read how Flatpak works, more specifically: how (confined) sandboxed applications work. Still, there are some things that are really tricky to make it work. Usually SDKs installed by the operating system are not  easy to integrate, so just use a package manager that install in your home directory (should be the standard these days for developers) — you shouldn't have many problems after this.

Feel free to ask for help in the Flathub's Discourse.
