### ISSUE TITLE
IDEA version displayed wrongly in `flatpak list` command in terminal

### ISSUE THREAD

**Issue by topazus** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#95]
It seems that recently [commit](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/commit/65272ea740b41973f95caa1f33f91795223bf253) update of IDEA to version 2021.3.1, but I installed it today in terminal and the displayed version number may be wrong, which is 2021.2.

```
# flatpak list 
Name                         Application ID                                  Version       Branch       Installation
IntelliJ IDEA Ultimate       com.jetbrains.IntelliJ-IDEA-Ultimate            2021.2        stable       system
Mesa                         org.freedesktop.Platform.GL.default             21.3.3        21.08        system
nvidia-495-46                org.freedesktop.Platform.GL.nvidia-495-46                     1.4          system
Intel                        org.freedesktop.Platform.VAAPI.Intel                          21.08        system
openh264                     org.freedesktop.Platform.openh264               2.1.0         2.0          system
Freedesktop SDK              org.freedesktop.Sdk                             21.08.8       21.08        system
```
when I open the IDEA flatpak application, its version is 2021.3.1.
![image](https://user-images.githubusercontent.com/77263945/148354910-a31b1ff9-1b50-4465-b5c4-5bf0d037da72.png)

**Comment by x80486** [comment]
This is because the automatic update, somehow, couldn't update the required fields in the AppStream Metadata file (`*.metainfo.xml`). I did forget to check if it was updated 😏

I _refreshed_ the issue I filed in JetBrains' YouTrack for IDEA to see if they finally consider shipping this file by default. It really makes no sense that this application does not include it yet.

**Comment by x80486** [comment]
@topazus, I'm going to close this one since it was an error when merging the AppStream Metadata file, rather than an issue with the IDE itself. Feel free to reopen it or open a new one instead.
