### ISSUE TITLE
GPG Git commit signing doesn't work

### ISSUE THREAD

**Issue by skidunion** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#98]
When trying to commit with signing enabled, the following message appears:

```
0 file committed, 1 file failed to commit: <commit> 
gpg failed to sign the data
failed to write commit object
```

If I try to sign some cleartext with GPG (`echo "test" | gpg --clearsign`), via IDEA's Terminal tab, it becomes clear that the error is caused by missing pinentry:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

test
gpg: signing failed: No pinentry
gpg: [stdin]: clear-sign failed: No pinentry
```

Similar issue exists in the community version: https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Community/issues/62, but was solved by bundling pinentry

**Comment by x80486** [comment]
@skidunion, let me know if the  pull request associated to this issue fixes the problem.

**Comment by skidunion** [comment]
![Screenshot_20220408_003452](https://user-images.githubusercontent.com/34306421/162323911-b38177f5-0ffc-4178-acfa-09c8226b5fe3.png)
Appears to be working now, thanks
